WIN_WIDTH = 620
WIN_HEIGHT = 465
TILESIZE = 31
FPS = 60

PLAYER_LAYER = 4
ENEMY_LAYER = 3
BLOCK_LAYER = 2
GROUND_LAYER = 1

PLAYER_SPEED = 2.4
ENEMY_SPEED = 0.4

RED = (255, 0, 0)
BLACK = (0 , 0, 0)
BLUE = (0, 0, 255)
WHITE = (255,255,255)

tilemap = [ 
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBB.E.....BBBBBBBBBBBBBBBBBBB.BB..............BB...NBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBB.............BB.N..BB.....................BB........BBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBB.............BB....BB....................BB........BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBN.BB............BB....BB....BBBBBBBBBB......BB........BBBBBBBBBBBBBBB',
    'BBBBBBBBBBB....BB..........BB....BB....................BB........BBBBBBBBBBBBBBB',
    'BBBBBBBBBBB......BB........BB....BB.........P..........BB........BBBBBBBBBBBBBBB',
    'BBBBBBBBBBB........BB......BB....BB....................BB........BBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBB.........B.............BB...BB....BB................BBBBBBBBBBBBBB',
    'BBBBBBBBBBBNBB...BB.................BB....BB....BB.................BBBBBBBBBBBBB',
    'BBBBBBBBBBB.......BB............BBBBB......BB....BB..B..............NBBBBBBBBBBB',
    'BBBBBBBBBBBB.......BB.......BBB..................BB.....B........BBBBBBBBBBBBBBB',
    'BBBBBBBBBBB..........BB...BB..............BB.......BB....B............BBBBBBBBBB',
    'BBBBBBBBBBB........B...BBB..........B....BB.........BB...............BBBBBBBBBBB',
    'BBBBBBBBBBBB.....B..B..B..B.B..B.......BB...........BB...........BBBBBBBBBBBBBBB',
    'BBBBBBBBBBB..B....B...B..B....B...B...BB...B..........BB............BBBBBBBBBBBB',
    'BBBBBBBBBBB..B.B.B..B....B..B...B...BB...............B...............BBBBBBBBBBB',
    'BBBBBBBBBBB........B....B....B..B..BBB.........B.......BB.......B.....BBBBBBBBBB',
    'BBBBBBBBBBBN.....B...B....B....B..BBN...........B.........B...........BBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

# Definição dos pesos para cada tipo de tile (você pode ajustar conforme desejado)
TILE_WEIGHTS = {
    '.': 1,   # chão normal
    'E': 1,   # célula onde um inimigo pode estar (apesar de ser gerada dinamicamente, o valor pode ser 1)
    'N': 3,   # notas podem ter um custo um pouco maior (fazendo o Slenderman “evitar” esses caminhos, se for desejado)
    'P': 1,
    'B': 999   # célula do jogador (destino final do pathfinding)
    # outros tipos de tile podem ser adicionados aqui se necessário
}